export {
    IconSettingsCode,
    IconBrandHtml5,
    IconBrandCss3,
    IconBrandSass,
    IconBrandBootstrap,
    IconBrandTailwind,
    IconBrandJavascript,
    IconBrandReact,
    IconBrandTypescript,
    IconBrandNodejs,
    IconBrandPnpm,
    IconBrandNpm,
    IconBrandPhp,
    IconBrandLaravel,
    IconRoute,
    IconBrandAzure,
    IconBrandVercel,
    IconCloud,
    IconFileTypeJs,
    IconBrandGit,
    IconBrandGithub,
    IconBrandMysql,
    IconFlask,
    IconBrandCSharp
} from "@tabler/icons-react"